[package]
name = "db_init"
version = "0.1.0"
edition = "2021"

[dependencies]
# Database
sqlx = { version = "0.8.6", default-features = false, features = [
    "runtime-tokio-rustls",
    "migrate",
] }

# Async runtime
tokio = { version = "1.49.0", features = ["rt"] }

# Logging
tracing = "0.1"

[features]
default = []
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]
sqlite = ["sqlx/sqlite"]
