[package]
name = "stitch_images"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = {version = "0.5.1", features = ["json"]}
db_init = { path = "../crates/db_init", features = ["postgres"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json", "migrate"] }
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15.7"
uuid = { version = "1.23.1", features = ["serde", "v7"] }
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt", "registry"] }
tracing-opentelemetry = "0.33.0"
opentelemetry = { version = "0.31.0", features = ["metrics", "trace", "logs"] }
opentelemetry_sdk = { version = "0.31.0", features = ["metrics", "trace", "logs", "rt-tokio"] }
opentelemetry-otlp = { version = "0.31.0", features = ["http-proto", "reqwest-blocking-client", "trace", "metrics", "logs"] }
opentelemetry-appender-tracing = "0.31.1"

image = "0.25.9"
rayon = "1.11.0"
exif = { package = "kamadak-exif", version = "0.6" }
maud = "0.27.0"
