services:
  todo_web:
    build:
      context: ..
      dockerfile: todo_web/Dockerfile
    image: ${TODO_WEB_IMAGE:-todo_web:latest}
    container_name: todo_web
    ports:
      - "${SERVICE_PORT:-3000}:${SERVICE_PORT:-3000}"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-services}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA:-todo_web}
      CACHE_HOST: cache
      CACHE_PORT: ${CACHE_PORT:-6379}
      RUST_LOG: debug
      ASSETS_LOCATION: /app/assets
      SERVICE_PORT: ${SERVICE_PORT:-3000}
      OTEL_EXPORTER_OTLP_ENDPOINT: localhost:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=todo_web
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: todo_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-services}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: todo_redis
    restart: unless-stopped
    ports:
      - "${CACHE_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN:-}
    container_name: cloudflared
    restart: unless-stopped
    profiles:
      - prod

networks:
  default:


volumes:
  postgres_data:
    driver: local
