services:
  todo_web:
    image: raspberrypi.local:5000/todo_web:latest
    container_name: todo_web
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RUST_LOG: info
      ASSETS_LOCATION: /app/assets
      SERVICE_PORT: ${SERVICE_PORT}
    volumes:
      - ./data:/app/data
      - ./assets:/app/assets
    restart: unless-stopped

  db:
    image: postgres
    container_name: todo_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      PG_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN
    container_name: cloudflared
    restart: unless-stopped
    profiles:
      - prod

networks:
  default:


volumes:
  postgres_data:
    driver: local
