run:
    DATABASE_LOCATION=./todo_data/todo.db PORT=3000 ASSETS_LOCATION=./assets cargo run                                                        

deploy:
    ssh -Y pi@raspberrypi.local 'bash -s' < ./scripts/deploy-service.sh

update-repo:
    ssh -Y pi@raspberrypi.local 'bash -s' < ./scripts/update-repo.sh